workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    
    environment:
      node: 20
      xcode: latest
      cocoapods: default
      groups:
        - ios-dev
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
    
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
      cancel_previous_builds: true
    
    scripts:
      - name: Set version from tag
        script: |
          # Extract version from tag (remove 'v' prefix)
          APP_VERSION=${CM_TAG#v}
          echo "Building version: $APP_VERSION"
          echo "APP_VERSION=$APP_VERSION" >> $CM_ENV
          
      - name: Install dependencies
        script: |
          npm ci
          
      - name: Install Expo CLI and EAS CLI
        script: |
          npm install -g expo-cli eas-cli
          
      - name: Run Expo Prebuild
        script: |
          npx expo prebuild --platform ios --clean
          
      - name: Install CocoaPods
        script: |
          cd ios && pod install
          
      - name: Build unsigned iOS App
        script: |
          cd ios
          # Get the workspace and scheme names
          WORKSPACE=$(ls -d *.xcworkspace | head -1)
          SCHEME=$(echo $WORKSPACE | sed 's/.xcworkspace//')
          echo "Building $SCHEME from $WORKSPACE"
          
          xcodebuild -workspace "$WORKSPACE" \
            -scheme "$SCHEME" \
            -configuration Release \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            -archivePath $CM_BUILD_DIR/build.xcarchive \
            archive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            AD_HOC_CODE_SIGNING_ALLOWED=YES
            
      - name: Create IPA
        script: |
          mkdir -p $CM_BUILD_DIR/Payload
          cp -r $CM_BUILD_DIR/build.xcarchive/Products/Applications/*.app $CM_BUILD_DIR/Payload/
          cd $CM_BUILD_DIR
          zip -r paperand-${APP_VERSION}.ipa Payload
          rm -rf Payload
    
    artifacts:
      - "*.ipa"
    
    publishing:
      email:
        recipients:
          - chiraitori.dev@gmail.com
        notify:
          success: true
          failure: true
      
      scripts:
        - name: Upload IPA to existing GitHub Release
          script: |
            # Wait a bit for GitHub Actions to create the release first
            sleep 60
            
            # Find the IPA file
            IPA_FILE=$(find $CM_BUILD_DIR -name "*.ipa" -type f | head -1)
            if [ -z "$IPA_FILE" ]; then
              echo "No IPA file found!"
              exit 1
            fi
            
            IPA_NAME=$(basename "$IPA_FILE")
            echo "Uploading $IPA_NAME to release $CM_TAG"
            
            # Get the release by tag
            RELEASE_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/chiraitori/paperand/releases/tags/$CM_TAG")
            
            RELEASE_ID=$(echo "$RELEASE_INFO" | jq -r '.id')
            
            if [ "$RELEASE_ID" == "null" ] || [ -z "$RELEASE_ID" ]; then
              echo "Release not found for tag $CM_TAG, creating new one..."
              # Create a new release if not exists
              RELEASE_INFO=$(curl -s -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: application/json" \
                -d "{\"tag_name\": \"$CM_TAG\", \"name\": \"📱 Paperand ${CM_TAG#v}\", \"prerelease\": true}" \
                "https://api.github.com/repos/chiraitori/paperand/releases")
              RELEASE_ID=$(echo "$RELEASE_INFO" | jq -r '.id')
            fi
            
            echo "Release ID: $RELEASE_ID"
            
            # Upload the IPA to the release
            curl -s -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/octet-stream" \
              --data-binary @"$IPA_FILE" \
              "https://uploads.github.com/repos/chiraitori/paperand/releases/$RELEASE_ID/assets?name=$IPA_NAME"
            
            echo "✅ IPA uploaded successfully!"
